### ISSUE TITLE
Find second API and make sure it works with JS

### ISSUE THREAD

**Issue by davidyeungcoding** [Americone-Dream/Loiter#15]

**Comment by yeungpirate** [comment]
HERE API:
https://developer.here.com/documentation/places/topics/quick-start-find-text-string.html
https://places.cit.api.here.com/places/v1/discover/search#
-90 day limit
-15000 request per month
-Check slack group chat for API info

Alternate API -> Open Table:
https://platform.opentable.com/documentation/#directory
