### ISSUE TITLE
Get search bar working with API

### ISSUE THREAD

**Issue by davidyeungcoding** [Americone-Dream/Loiter#21]

**Comment by yeungpirate** [comment]
Sample of Functioning Search:
https://api.seatgeek.com/2/recommendations?performers.id=35&client_id=MTE2OTc1MDh8MTUyNzEzODIxMC42Mw

NOTE: 
Search is referencing performers.id and not performers.name. Documentation states that acceptable requests refer to the IDs (event / name).

**Comment by yeungpirate** [comment]
Added function for events locally based off of the user's IP. Tested successfully, but currently not associated with any event, waiting on addition to HTML.

**!!Additional Notes (Important)!!:** 
Changes have been made to variables to make them more unique and easier to tell what they are used for.
