### ISSUE TITLE
Get search results to populate new page

### ISSUE THREAD

**Issue by davidyeungcoding** [Americone-Dream/Loiter#26]

**Comment by yeungpirate** [comment]
## Thoughts on how to get this to work:

### For Search Results:
- Have a global var that contains what the user typed (not sure if it's possible to reference a var from a different doc)
- When the new page loads, have the the js run the search request against the API and populate the new page

### For Local Events:
- Been working on this one where the link for **Events Near Me** will just redirect the user to a new page
- On the new page I have the system run the search for local events
- Working on getting results to create new divs with information from the results
- We'll have to look into how to setup pagination to store additional results
