### ISSUE TITLE
Materialize styling for landing page

### ISSUE THREAD

**Issue by nmclear** [Americone-Dream/Loiter#9]
Styling to make the landing page sleek and professional. Color and font style needed.

**Comment by yeungpirate** [comment]
I've added the console.log() to the Events Near Me feature. It doesn't feel right without having the mouse change when hovering over it. Maybe consider making it a link?

**Comment by yeungpirate** [comment]
Noticed a couple more things:

- For the Buy Now button, is there a way to get it to be fixed at the bottom of the card? Not 100% necessary, but I think it might look better. 

- Also, can we get the cards to be restricted to a certain size? I think it'll look better if all cards were uniformed in look.

**Comment by 2juicy** [comment]
I found something we could possibly use for styling, if you guys got a minute check this out
https://daneden.github.io/animate.css/

**Comment by yeungpirate** [comment]
Went over that link, some really cool stuff there.

**Comment by nmclear** [comment]
Great find on the link. Nirav and I will work on adding some animations.

**Comment by nmclear** [comment]
I added the pointer cursor to the events near me button. The buy now button is fixed to bottom of the card when card details is open. I'll work on the card height issue next.
